import "./posts.css";
import landscapeImg from "../../../Assets/landscape_1.png";
import {
  Particle,
  eraseCookies,
  getDate,
  backendHostAddr,
} from "../../../Utils";

import { useState, useEffect } from "react";
import { Col, Container } from "react-bootstrap";

// single post
function Post(props: any) {
  return props.post ? (
    <div className="post">
      <a
        href={"#/post/" + props.post.id}
        style={{ textDecoration: "none", color: "black" }}
      >
        <img className="postImg" src={landscapeImg} alt=""></img>
        <div className="postInfo">
          <div className="postCategories">
            {/* <span className="postCategory">
                            Entire post was generated by AI
                        </span> */}
          </div>
          <span className="postTitle">{props.post.title}</span>
          <span className="postDate">{getDate(props.post.date)}</span>
        </div>
      </a>
      <p className="postDesc">{props.post.description}</p>
    </div>
  ) : null;
}

function getPosts(posts: any) {
  try {
    return posts.map((post: any) => {
      return (
        <Col key={post.id}>
          <Post post={post} />
        </Col>
      );
    });
  } catch {
    return eraseCookies();
  }
}

export default function Posts() {
  const [posts, setPosts] = useState<any>([]);
  const cookies = `Token ${document.cookie.split("=")[1]}`;

  useEffect(() => {
    if (!document.cookie) {
      window.location.replace("#/login");
      window.location.reload();
    }

    fetch(`${backendHostAddr}/api/posts/`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: cookies,
      },
    })
      .then((resp: any) => resp.json())
      .then((resp: any) => setPosts(resp))
      .catch((error: any) => console.log(error));
  }, [cookies]);

  return posts ? (
    <Container className="posts">
      <Particle />
      {getPosts(posts)}
    </Container>
  ) : (
    <Container></Container>
  );
}
