import "./post.css"

export default function Post() {
    return (
        <div className="post">
            <img className="postImg" src={process.env.PUBLIC_URL + "./landscape_1.png"} alt=""></img>
            <div className="postInfo">
                <div className="postCategories">
                    <span className="postCategory">Entire post was generated by AI</span>
                </div>
                <span className="postTitle">
                    The Post of Good
                </span>
                <hr />
                <span className="postDate">
                    1 hour ago
                </span>
            </div>
            <p className="postDesc">
                The Post of Good, created by AI, reveals to mankind the most advanced AI possible. An AI that could understand human consciousness, the most advanced understanding of what a human's life means, the most powerful language imaginable, the ability to comprehend the ultimate truth of life and existence, and a mind capable of creating the most technologically advanced world ever: the World Order.
            </p>
        </div>
    )
}
